//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradingAddin.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"9E49BEBE4160B4AB946CED32E26C1EAC946CED32E26C1EAC946CED32E26C1EAC946CED32E26C1EAC946CED32E26C1EACAE278E1FDBF325F7466B2F83E0CF8B2C946CED32E26C1EACE0ED6D092F5FB869CED0792D0AE74E02946CED32E26C1EACD33D6030790F8965FDCD684DF49C6F3147D3EA0BF4E191F504150D6FCCEAEB6E876A14E909AF616FBB0E093F8D18BEF83AF65FC9D653F4834E9D87FFA878DF9D815C4133049127BC74BA272499C295E99E049D0636ED748E33D68D95D921BE4EDD9594FE0C28B18005670F1C9A7829B60EC69CD64BFC0D2F2A61F88F38E3A026F05B3DE163831EB84E73144F5F96B73A0826D24C7A775D51C02F735D22F1D3F8")]
        public string ESunny_Global_Trade_AuthCode {
            get {
                return ((string)(this["ESunny_Global_Trade_AuthCode"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("202.55.1.53")]
        public string ESunny_Global_Trade_IP {
            get {
                return ((string)(this["ESunny_Global_Trade_IP"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15858")]
        public ushort ESunny_Global_Trade_Port {
            get {
                return ((ushort)(this["ESunny_Global_Trade_Port"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C7201")]
        public string ESunny_Global_Trade_UserNo {
            get {
                return ((string)(this["ESunny_Global_Trade_UserNo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("123456")]
        public string ESunny_Global_Trade_Password {
            get {
                return ((string)(this["ESunny_Global_Trade_Password"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Xuhaoyun@gmail.com")]
        public string ESunny_Global_Trade_ContactInfo {
            get {
                return ((string)(this["ESunny_Global_Trade_ContactInfo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("client_PureArb_1.0.0")]
        public string ESunny_Domestic_Trade_AuthCode {
            get {
                return ((string)(this["ESunny_Domestic_Trade_AuthCode"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("client_PureArb_1.0.0")]
        public string ESunny_Domestic_Trade_AppID {
            get {
                return ((string)(this["ESunny_Domestic_Trade_AppID"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("115.238.106.253")]
        public string ESunny_Domestic_Trade_IP {
            get {
                return ((string)(this["ESunny_Domestic_Trade_IP"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6868")]
        public ushort ESunny_Domestic_Trade_Port {
            get {
                return ((ushort)(this["ESunny_Domestic_Trade_Port"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("70510077")]
        public string ESunny_Domestic_Trade_UserNo {
            get {
                return ((string)(this["ESunny_Domestic_Trade_UserNo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("111111")]
        public string ESunny_Domestic_Trade_Password {
            get {
                return ((string)(this["ESunny_Domestic_Trade_Password"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"B112F916FE7D27BCE7B97EB620206457946CED32E26C1EAC946CED32E26C1EAC946CED32E26C1EAC946CED32E26C1EAC5211AF9FEE541DDE9D6F622F72E25D5DEF7F47AA93A738EF5A51B81D8526AB6A9D19E65B41F59D6A946CED32E26C1EACCAF8D4C61E28E2B1ABD9B8F170E14F8847D3EA0BF4E191F5DCB1B791E63DC196D1576DEAF5EC563CA3E560313C0C3411B45076795F550EB050A62C4F74D5892D2D14892E812723FAC858DEBD8D4AF9410729FB849D5D8D6EA48A1B8DC67E037381A279CE9426070929D5DA085659772E24A6F5EA52CF92A4D403F9E46083F27B19A88AD99812DADA44100324759F9FD1964EBD4F2F0FB50B51CD31C0B02BB437")]
        public string ESunny_Global_Quote_AuthCode {
            get {
                return ((string)(this["ESunny_Global_Quote_AuthCode"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("61.163.243.173")]
        public string ESunny_Global_Quote_IP {
            get {
                return ((string)(this["ESunny_Global_Quote_IP"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7171")]
        public ushort ESunny_Global_Quote_Port {
            get {
                return ((ushort)(this["ESunny_Global_Quote_Port"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ES")]
        public string ESunny_Global_Quote_UserNo {
            get {
                return ((string)(this["ESunny_Global_Quote_UserNo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("123456")]
        public string ESunny_Global_Quote_Password {
            get {
                return ((string)(this["ESunny_Global_Quote_Password"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"B112F916FE7D27BCE7B97EB620206457946CED32E26C1EAC946CED32E26C1EAC946CED32E26C1EAC946CED32E26C1EAC5211AF9FEE541DDE9D6F622F72E25D5DEF7F47AA93A738EF5A51B81D8526AB6A9D19E65B41F59D6A946CED32E26C1EACCAF8D4C61E28E2B1ABD9B8F170E14F8847D3EA0BF4E191F5DCB1B791E63DC196D1576DEAF5EC563CA3E560313C0C3411B45076795F550EB050A62C4F74D5892D2D14892E812723FAC858DEBD8D4AF9410729FB849D5D8D6EA48A1B8DC67E037381A279CE9426070929D5DA085659772E24A6F5EA52CF92A4D403F9E46083F27B19A88AD99812DADA44100324759F9FD1964EBD4F2F0FB50B51CD31C0B02BB437")]
        public string ESunny_Domestic_Quote_AuthCode {
            get {
                return ((string)(this["ESunny_Domestic_Quote_AuthCode"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("61.163.243.173")]
        public string ESunny_Domestic_Quote_IP {
            get {
                return ((string)(this["ESunny_Domestic_Quote_IP"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7171")]
        public ushort ESunny_Domestic_Quote_Port {
            get {
                return ((ushort)(this["ESunny_Domestic_Quote_Port"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ES")]
        public string ESunny_Domestic_Quote_UserNo {
            get {
                return ((string)(this["ESunny_Domestic_Quote_UserNo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("123456")]
        public string ESunny_Domestic_Quote_Password {
            get {
                return ((string)(this["ESunny_Domestic_Quote_Password"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tcp://115.238.106.252:41327")]
        public string CTP_Stock_Trade_Address {
            get {
                return ((string)(this["CTP_Stock_Trade_Address"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8050")]
        public string CTP_Stock_Trade_BrokerID {
            get {
                return ((string)(this["CTP_Stock_Trade_BrokerID"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("90099529")]
        public string CTP_Stock_Trade_UserID {
            get {
                return ((string)(this["CTP_Stock_Trade_UserID"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("666666")]
        public string CTP_Stock_Trade_Password {
            get {
                return ((string)(this["CTP_Stock_Trade_Password"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TC7MAYPGDEW2PE3D")]
        public string CTP_Stock_Trade_AuthCode {
            get {
                return ((string)(this["CTP_Stock_Trade_AuthCode"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("client_PureArb_1.0.0")]
        public string CTP_Stock_Trade_AppID {
            get {
                return ((string)(this["CTP_Stock_Trade_AppID"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tcp://115.238.106.252:41207")]
        public string CTP_Future_Trade_Address {
            get {
                return ((string)(this["CTP_Future_Trade_Address"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tcp://115.238.106.252:41315")]
        public string CTP_Future_MD_Address {
            get {
                return ((string)(this["CTP_Future_MD_Address"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1008")]
        public string CTP_Future_Trade_BrokerID {
            get {
                return ((string)(this["CTP_Future_Trade_BrokerID"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("90100951")]
        public string CTP_Future_Trade_UserID {
            get {
                return ((string)(this["CTP_Future_Trade_UserID"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("abc9978217")]
        public string CTP_Future_Trade_Password {
            get {
                return ((string)(this["CTP_Future_Trade_Password"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WK1JU573429UXGLM")]
        public string CTP_Future_Trade_AuthCode {
            get {
                return ((string)(this["CTP_Future_Trade_AuthCode"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("client_PureArb_1.0.0")]
        public string CTP_Future_Trade_AppID {
            get {
                return ((string)(this["CTP_Future_Trade_AppID"]));
            }
        }
    }
}
